routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /api/courses/:
    template: api/course
    content_type: json
collections:
  /courses/:
    permalink: /courses/{slug}/
    filter: tag:course
  /blog/:
    permalink: /blog/{slug}/
    filter: tag:blog
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /topic/{slug}/
  author: /author/{slug}/
