routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account

collections:
  /blog/:
    permalink: /blog/{slug}/
    filter: tag:blog
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
